
CREATE DATABASE crm;
USE crm;

CREATE TABLE users(
 id INT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(255),
 email VARCHAR(255),
 password VARCHAR(255)
);

CREATE TABLE leads(
 id INT AUTO_INCREMENT PRIMARY KEY,
 name VARCHAR(255),
 contact VARCHAR(255),
 owner VARCHAR(255),
 value DECIMAL(10,2)
);
